get:
  summary: List Sources
  description: Returns a list of sources. Sources are where works are hosted, including journals, conferences, preprint repositories, and institutional repositories.
  parameters:
    - $ref: '../components/parameters/filter_parameter.yaml'
    - $ref: '../components/parameters/search_parameter.yaml'
    - $ref: '../components/parameters/sort_parameter.yaml'
    - $ref: '../components/parameters/page_parameter.yaml'
    - $ref: '../components/parameters/per_page_parameter.yaml'
    - $ref: '../components/parameters/select_parameter.yaml'
    - $ref: '../components/parameters/group_by_parameter.yaml'
    - name: sample
      in: query
      description: Get a random sample of results
      schema:
        type: integer
      example: 10
  responses:
    '200':
      description: Successful response
      content:
        application/json:
          schema:
            type: object
            properties:
              meta:
                $ref: '../components/schemas/meta.yaml'
              results:
                type: array
                items:
                  $ref: '../components/schemas/source.yaml'
              group_by:
                type: array
                items:
                  $ref: '../components/schemas/group_by.yaml'
    '400':
      description: Bad request
    '403':
      description: Forbidden
    '429':
      description: Too many requests

/{id}:
  get:
    summary: Get a single Source
    description: Returns details for a single source. Any ID supported in the `ids` object will successfully return a single entity.
    parameters:
      - name: id
        in: path
        required: true
        description: OpenAlex ID or any supported external ID (ISSN, ISSN-L, MAG, Wikidata) of the source
        schema:
          type: string
      - $ref: '../components/parameters/select_parameter.yaml'
    responses:
      '200':
        description: Successful response
        content:
          application/json:
            schema:
              $ref: '../components/schemas/source.yaml'
      '404':
        description: Source not found
      '403':
        description: Forbidden
      '429':
        description: Too many requests

/autocomplete:
  get:
    summary: Autocomplete Sources
    description: Returns a list of sources for autocomplete functionality.
    parameters:
      - name: q
        in: query
        description: The search query for autocomplete
        required: true
        schema:
          type: string
    responses:
      '200':
        description: Successful response
        content:
          application/json:
            schema:
              type: object
              properties:
                results:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                        description: The OpenAlex ID for this source
                      display_name:
                        type: string
                        description: The name of the source
                      hint:
                        type: string
                        description: Additional information (usually the publisher)
                      cited_by_count:
                        type: integer
                        description: The number of citations to works in this source
                      works_count:
                        type: integer
                        description: The number of works in this source
                      entity_type:
                        type: string
                        enum: [source]
                      external_id:
                        type: string
                        description: An external identifier for this source (usually ISSN)
              example:
                results:
                  - id: "https://openalex.org/S5555990"
                    display_name: "The Journal of Neuroscience"
                    hint: "Society for Neuroscience"
                    cited_by_count: 4274712
                    works_count: 40376
                    entity_type: "source"
                    external_id: "0270-6474"
      '400':
        description: Bad request
      '403':
        description: Forbidden
      '429':
        description: Too many requests
