openapi: 3.0.0
info:
  title: OpenAlex API
  description: An OpenAPI specification for the OpenAlex API
  version: 1.0.0
servers:
  - url: https://api.openalex.org/
paths:
  /authors:
    $ref: ./paths/authors.yaml
  /concepts:
    $ref: ./paths/concepts.yaml
  /funders:
    $ref: ./paths/funders.yaml
  /institutions:
    $ref: ./paths/institutions.yaml
  /keywords:
    $ref: ./paths/keywords.yaml
  /publishers:
    $ref: ./paths/publishers.yaml
  /sources:
    $ref: ./paths/sources.yaml
  /topics:
    $ref: ./paths/topics.yaml
  /works:
    $ref: ./paths/works.yaml
  
components:
  $ref: './components/index.yaml'
