openapi: 3.0.0
info:
  title: OpenAlex API
  description: An OpenAPI specification for the OpenAlex API
  version: 1.0.0
servers:
  - url: https://api.openalex.org/
paths:
  /authors:
    $ref: ./paths/authors.yaml
  /concepts:
    $ref: ./paths/concepts.yaml
  /funders:
    $ref: ./paths/funders.yaml
  /institutions:
    $ref: ./paths/institutions.yaml
  /keywords:
    $ref: ./paths/keywords.yaml
  /publishers:
    $ref: ./paths/publishers.yaml
  /sources:
    $ref: ./paths/sources.yaml
  /topics:
    $ref: ./paths/topics.yaml
  /works:
    $ref: ./paths/works.yaml
  /concepts:
    $ref: ./paths/concepts.yaml
  /autocomplete/{entity_type}:
    get:
      summary: Autocomplete entities
      description: Returns a list of entities that match the given query string for autocomplete suggestions.
      parameters:
        - name: entity_type
          in: path
          required: true
          schema:
            type: string
            enum: [authors, concepts, funders, institutions, publishers, sources, topics, works]
        - $ref: '#/components/parameters/autocomplete'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Autocomplete'
  
components:
  $ref: './components/index.yaml'
