openapi: 3.0.0
info:
  title: OpenAlex API
  description: An OpenAPI specification for the OpenAlex API
  version: 1.0.0
servers:
  - url: https://api.openalex.org/
paths:
  /authors:
    $ref: ./paths/authors.yaml
  /concepts:
    $ref: ./paths/concepts.yaml
  /funders:
    $ref: ./paths/funders.yaml
  /institutions:
    $ref: ./paths/institutions.yaml
  /keywords:
    $ref: ./paths/keywords.yaml
  /publishers:
    $ref: ./paths/publishers.yaml
  /sources:
    $ref: ./paths/sources.yaml
  /topics:
    $ref: ./paths/topics.yaml
  /works:
    $ref: ./paths/works.yaml
  /autocomplete/authors:
    $ref: ./paths/autocomplete_authors.yaml
  /autocomplete/concepts:
    $ref: ./paths/autocomplete_concepts.yaml
  /autocomplete/funders:
    $ref: ./paths/autocomplete_funders.yaml
  /autocomplete/institutions:
    $ref: ./paths/autocomplete_institutions.yaml
  /autocomplete/publishers:
    $ref: ./paths/autocomplete_publishers.yaml
  /autocomplete/sources:
    $ref: ./paths/autocomplete_sources.yaml
  /autocomplete/topics:
    $ref: ./paths/autocomplete_topics.yaml
  /autocomplete/works:
    $ref: ./paths/autocomplete_works.yaml
  
components:
  $ref: './components/index.yaml'
